version: '2'
services:
  db:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_PASSWORD=test-password    

  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RAILS_ENV=production
      - TOPSCORE_DATABASE_URL=postgres://postgres:test-password@db/postgres
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=d40a2025915eb4d0ab95771dc7148951995341f93e33bcb2c3ab2d68fe13aaeee627a02a822ae9c0abb1680d49c8fd9b48b69007988dde98ae7bbeb86ddb9c46
    volumes:
      - .:/app
    expose:
      - "3000"
    links:
      - db
    depends_on:
      - db

  nginx:
    image: nginx:1.19.10-alpine
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - web-api
